#!/usr/bin/env bash
# IVX Multiplayer codegen — emits TS + C# from schemas/multiplayer/*.proto.
#
# P0 deliverable. Future waves extend with Unreal/C++, Godot, Flutter, Java.
#
# Requires:
#   - protoc                       (>= 3.21)
#   - grpc-tools (npm)             for ts-proto plugin discovery (optional)
#   - protoc-gen-ts_proto          (npm i -g ts-proto) — preferred TS gen
#   - dotnet >= 6                  for C# gen via Grpc.Tools fallback path
#
# Usage:
#   ./tools/codegen/gen-multiplayer.sh           # emit TS + C#
#   ./tools/codegen/gen-multiplayer.sh ts        # TS only
#   ./tools/codegen/gen-multiplayer.sh csharp    # C# only
#   CHECK=1 ./tools/codegen/gen-multiplayer.sh   # diff-only mode (CI)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCHEMA_ROOT="$REPO_ROOT/schemas/multiplayer"

TS_OUT="$REPO_ROOT/SDKs/javascript/packages/multiplayer/src/wire"
CS_OUT="$REPO_ROOT/Assets/_IntelliVerseXSDK/Multiplayer/Generated"

LANGS="${1:-all}"

log() { printf '[codegen] %s\n' "$*"; }

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "ERROR: required tool '$1' not found in PATH."
    log "Install hint: $2"
    exit 1
  fi
}

resolve_protos() {
  find "$SCHEMA_ROOT" -name '*.proto' -type f | sort
}

# ---------- TypeScript ----------

gen_ts() {
  log "Generating TypeScript bindings → $TS_OUT"
  mkdir -p "$TS_OUT"
  require protoc "https://github.com/protocolbuffers/protobuf/releases"

  local ts_plugin
  ts_plugin="$(command -v protoc-gen-ts_proto || true)"
  if [[ -z "$ts_plugin" ]]; then
    log "WARN: protoc-gen-ts_proto not found; falling back to protoc --js_out + d.ts."
    log "      Install: npm i -g ts-proto"
    protoc \
      --proto_path="$SCHEMA_ROOT" \
      --js_out="import_style=commonjs,binary:$TS_OUT" \
      $(resolve_protos)
    return
  fi

  protoc \
    --proto_path="$SCHEMA_ROOT" \
    --plugin=protoc-gen-ts_proto="$ts_plugin" \
    --ts_proto_out="$TS_OUT" \
    --ts_proto_opt=outputServices=false,esModuleInterop=true,oneof=unions,useExactTypes=false,enumsAsLiterals=false,fileSuffix=.gen \
    $(resolve_protos)

  cat > "$TS_OUT/index.ts" <<'EOF'
// AUTO-GENERATED by tools/codegen/gen-multiplayer.sh — DO NOT EDIT.
export * from './envelope.gen';
export * from './kernel.gen';
export * from './templates/sync_turn.gen';
export * from './templates/async_turn.gen';
export * from './templates/realtime_tick.gen';
export * from './templates/lobby_handoff.gen';
export * from './templates/tournament.gen';
export * from './templates/live_event.gen';
export * from './templates/persistent_party.gen';
export * from './templates/avatar_replication.gen';
export * from './templates/mixed_reality_anchor.gen';
export * from './templates/conversational_party.gen';
export * from './services/agent.gen';
export * from './services/moderation.gen';
export * from './games/quizverse.gen';
EOF
  log "TypeScript codegen complete."
}

# ---------- C# (Unity) ----------

gen_csharp() {
  log "Generating C# bindings → $CS_OUT"
  mkdir -p "$CS_OUT/Templates" "$CS_OUT/Services" "$CS_OUT/Games"
  require protoc "https://github.com/protocolbuffers/protobuf/releases"

  protoc \
    --proto_path="$SCHEMA_ROOT" \
    --csharp_out="$CS_OUT" \
    --csharp_opt=base_namespace=IntelliVerseX.Multiplayer.Wire \
    "$SCHEMA_ROOT/envelope.proto" \
    "$SCHEMA_ROOT/kernel.proto"

  protoc \
    --proto_path="$SCHEMA_ROOT" \
    --csharp_out="$CS_OUT/Templates" \
    --csharp_opt=base_namespace=IntelliVerseX.Multiplayer.Wire \
    "$SCHEMA_ROOT/templates/"*.proto

  protoc \
    --proto_path="$SCHEMA_ROOT" \
    --csharp_out="$CS_OUT/Services" \
    --csharp_opt=base_namespace=IntelliVerseX.Multiplayer.Wire \
    "$SCHEMA_ROOT/services/"*.proto

  protoc \
    --proto_path="$SCHEMA_ROOT" \
    --csharp_out="$CS_OUT/Games" \
    --csharp_opt=base_namespace=IntelliVerseX.Multiplayer.Wire \
    "$SCHEMA_ROOT/games/"*.proto

  cat > "$CS_OUT/IntelliVerseX.Multiplayer.Wire.asmdef" <<'EOF'
{
    "name": "IntelliVerseX.Multiplayer.Wire",
    "rootNamespace": "IntelliVerseX.Multiplayer.Wire",
    "references": [],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": true,
    "precompiledReferences": [
        "Google.Protobuf.dll"
    ],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
EOF

  cat > "$CS_OUT/README.md" <<'EOF'
# Generated wire types — DO NOT EDIT

Re-run `tools/codegen/gen-multiplayer.sh csharp` to regenerate.

`Google.Protobuf.dll` must be present under `Assets/Plugins/`. If it
isn't, run:

```
nuget install Google.Protobuf -OutputDirectory Assets/Plugins/Protobuf
```

or vendor it via a UPM scoped registry.
EOF
  log "C# codegen complete."
}

# ---------- main ----------

if [[ "$LANGS" == "ts" || "$LANGS" == "all" ]]; then gen_ts; fi
if [[ "$LANGS" == "csharp" || "$LANGS" == "all" ]]; then gen_csharp; fi

if [[ "${CHECK:-0}" == "1" ]]; then
  log "CHECK mode: verifying tree is clean..."
  if ! git diff --quiet -- "$TS_OUT" "$CS_OUT"; then
    log "ERROR: codegen produced diffs. Re-run gen-multiplayer.sh and commit."
    exit 1
  fi
  log "Tree clean."
fi

log "Done."
